CREATE TABLE `sigin_details` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `email` varchar(50) UNIQUE NOT NULL,
  `phoneNumber` varchar(20) NOT NULL,
  `gstNumber` varchar(30) NOT NULL,
  `aadharNumber` varchar(20) UNIQUE NOT NULL,
  `panNumber` varchar(20) UNIQUE NOT NULL,
  `address` varchar(250) NOT NULL,
  `shipmentType` varchar(50) NOT NULL,
  `paymentType` varchar(50) NOT NULL,
  `password` varchar(250) NOT NULL,
  `role` int NOT NULL,
  `status` int DEFAULT NULL,
  `authKey` varchar(200) DEFAULT NULL,
  `staffAccess` varchar(10) DEFAULT NULL,
  `val` varchar(50) DEFAULT NULL,
  `city` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `booking_details` (
  `id` int NOT NULL AUTO_INCREMENT,
  `senderName` varchar(50) NOT NULL,
  `senderEmail` varchar(50) NOT NULL,
  `senderPhoneNumber` varchar(20) NOT NULL,
  `senderCountry` varchar(20) NOT NULL,
  `senderCity` varchar(20) NOT NULL,
  `receiverName` varchar(20) NOT NULL,
  `receiverEmail` varchar(20) NOT NULL,
  `receiverPhoneNumber` varchar(20) NOT NULL,
  `receiverCountry` varchar(20) NOT NULL,
  `receiverCity` varchar(20) NOT NULL,
  `numberOfPieces` varchar(20) NOT NULL,
  `totalGrossWeight` varchar(20) NOT NULL,
  `grossWeightOfPieces` varchar(250) NOT NULL,
  `bookingStatus` int DEFAULT NULL,
  `bookingId` varchar(50) NOT NULL,
  `senderAddress` varchar(255) DEFAULT NULL,
  `senderBranchName` varchar(50) DEFAULT NULL,
  `senderPincode` varchar(20) DEFAULT NULL,
  `shipmentType` varchar(50) DEFAULT NULL,
  `paymentType` varchar(50) DEFAULT NULL,
  `receiverAddress` varchar(255) DEFAULT NULL,
  `receiverBranchname` varchar(50) DEFAULT NULL,
  `receiverPincode` varchar(50) DEFAULT NULL,
  `staffname` varchar(100) DEFAULT NULL,
  `staffCity` varchar(150) DEFAULT NULL,
  `amount` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `city_details` (
  `id` int NOT NULL AUTO_INCREMENT,
  `cityName` varchar(225) NOT NULL,
  `cityCode` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `city_details` (`id`, `cityName`, `cityCode`) VALUES
(3, 'madurai', 'MADU'),
(4, 'chennai', 'CHEN');


CREATE TABLE `shipment_details` (
  `id` int NOT NULL AUTO_INCREMENT,
  `shipmentType` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `shipment_details` (`id`, `shipmentType`) VALUES
(2, 'xyt');


CREATE TABLE `payment_details` (
  `id` int NOT NULL AUTO_INCREMENT,
  `paymentType` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `payment_details` (`id`, `paymentType`) VALUES
(1, 'Cheque');


CREATE TABLE images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bookingId VARCHAR(255) NOT NULL,
    path VARCHAR(255) NOT NULL,
    originalName VARCHAR(255) NOT NULL,
    uploadedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `pincodes` (
  `Sl.No` bigint DEFAULT NULL,
  `Pincode` bigint DEFAULT NULL,
  `Master Pincode` text,
  `District` text,
  `Taluk` text,
  `Village/Town` text,
  `Station` text,
  `Delivery line` text,
  `Service Available` text,
  `Delivery type` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `pincodes` (`Sl.No`, `Pincode`, `Master Pincode`, `District`, `Taluk`, `Village/Town`, `Station`, `Delivery line`, `Service Available`, `Delivery type`) VALUES
(1, 600001, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(2, 600002, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(3, 600002, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(4, 600003, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(5, 600004, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(6, 600005, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(7, 600006, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(8, 600007, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(9, 600008, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(10, 600009, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(11, 600010, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(12, 600011, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(13, 600012, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(14, 600013, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(15, 600014, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(16, 600015, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(17, 600017, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(18, 600018, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(19, 600020, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(20, 600021, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(21, 600022, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(22, 600023, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(23, 600024, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(24, 600025, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(25, 600026, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(26, 600028, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(27, 600030, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(28, 600031, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(29, 600032, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(30, 600033, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(31, 600034, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(32, 600035, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(33, 600036, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(34, 600038, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(35, 600039, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(36, 600040, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(37, 600041, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(38, 600042, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(39, 600078, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(40, 600081, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(41, 600082, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(42, 600083, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(43, 600084, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(44, 600085, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(45, 600086, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(46, 600090, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(47, 600092, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(48, 600093, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(49, 600094, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(50, 600101, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(51, 600102, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(52, 600104, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(53, 600106, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(54, 600107, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(55, 600113, 'No', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Chennai', 'Yes', 'Both'),
(56, 620001, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(57, 620002, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(58, 620003, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(59, 620004, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(60, 620005, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(61, 620006, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(62, 620007, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(63, 620008, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(64, 620009, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(65, 620010, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(66, 620011, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(67, 620012, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(68, 620013, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(69, 620014, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(70, 620015, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(71, 620016, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(72, 620017, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(73, 620018, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(74, 620019, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(75, 620020, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(76, 620021, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(77, 620022, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(78, 620023, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(79, 620024, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(80, 620025, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(81, 620026, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(82, 620027, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(83, 620101, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(84, 620102, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(85, 621001, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(86, 621002, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(87, 621003, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(88, 621004, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(89, 621005, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(90, 621006, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(91, 621007, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(92, 621008, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(93, 621009, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(94, 621010, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(95, 621011, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(96, 621012, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(97, 621014, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(98, 621101, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(99, 621102, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(100, 621103, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(101, 621104, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(102, 621105, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(103, 621106, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(104, 621109, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(105, 621110, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(106, 621111, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(107, 621112, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(108, 621114, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(109, 621118, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(110, 621202, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(111, 621203, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(112, 621204, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(113, 621205, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(114, 621206, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(115, 621207, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(116, 621208, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(117, 621209, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(118, 621210, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(119, 621211, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(120, 621213, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(121, 621214, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(122, 621215, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(123, 621216, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(124, 621217, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(125, 621218, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(126, 621220, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(127, 621601, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(128, 621651, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(129, 621652, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(130, 621653, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(131, 621702, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(132, 621703, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(133, 621706, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(134, 621708, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(135, 621711, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(136, 621712, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(137, 621722, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(138, 636001, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(139, 636002, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(140, 636003, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(141, 636004, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(142, 636005, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(143, 636006, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(144, 636007, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(145, 636008, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(146, 636009, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(147, 636010, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(148, 636011, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(149, 636012, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(150, 636013, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(151, 636014, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(152, 636015, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(153, 636016, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(154, 636017, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(155, 636030, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(156, 636101, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(157, 636102, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(158, 636103, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(159, 636104, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(160, 636105, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(161, 636106, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(162, 636107, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(163, 636108, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(164, 636109, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(165, 636110, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(166, 636111, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(167, 636112, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(168, 636113, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(169, 636114, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(170, 636115, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(171, 636116, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(172, 636117, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(173, 636118, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(174, 636119, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(175, 636121, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(176, 636122, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(177, 636138, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(178, 636139, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(179, 636140, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(180, 636141, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(181, 636142, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(182, 636201, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(183, 636202, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(184, 636203, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(185, 636204, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(186, 636302, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(187, 636303, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(188, 636304, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(189, 636305, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(190, 636306, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(191, 636307, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(192, 636308, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(193, 636309, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(194, 636351, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(195, 636354, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(196, 636401, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(197, 636402, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(198, 636403, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(199, 636404, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(200, 636406, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(201, 636451, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(202, 636452, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(203, 636453, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(204, 636454, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(205, 636455, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(206, 636456, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(207, 636457, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(208, 636458, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(209, 636501, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(210, 636502, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(211, 636503, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(212, 636601, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(213, 636602, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(214, 637501, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(215, 637502, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(216, 637504, 'NO', 'Salem', 'Salem', 'Salem', 'Salem', 'Salem', 'Yes', 'Both'),
(217, 639101, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(218, 639103, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(219, 639112, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(220, 639115, 'No', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Trichy', 'Yes', 'Both'),
(221, 641001, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(222, 641002, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(223, 641003, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(224, 641004, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(225, 641005, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(226, 641006, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(227, 641007, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(228, 641008, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(229, 641009, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(230, 641010, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(231, 641011, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(232, 641012, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(233, 641013, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(234, 641014, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(235, 641015, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(236, 641016, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(237, 641017, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(238, 641018, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(239, 641019, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(240, 641020, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(241, 641021, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(242, 641022, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(243, 641023, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(244, 641024, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(245, 641025, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(246, 641026, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(247, 641027, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(248, 641028, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(249, 641029, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(250, 641030, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(251, 641031, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(252, 641032, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(253, 641033, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(254, 641034, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(255, 641035, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(256, 641036, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(257, 641037, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(258, 641038, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(259, 641039, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(260, 641041, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(261, 641042, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(262, 641043, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(263, 641044, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(264, 641045, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(265, 641046, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(266, 641047, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(267, 641048, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(268, 641049, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(269, 641050, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(270, 641062, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(271, 641101, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(272, 641105, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(273, 641107, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(274, 641108, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(275, 641109, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(276, 641110, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(277, 641111, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(278, 641112, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(279, 641114, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both'),
(280, 641201, 'No', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Coimbatore', 'Yes', 'Both');


